name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ["14", "16", "18"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Update to latest npm
        run: npm install -g npm@latest
      - name: Install dependencies
        run: npm ci --include=dev
      - name: Lint with ESLint
        run: npm run lint
